### ISSUE TITLE
Chart is not show in combination with World Map plugin

### ISSUE THREAD

**Issue by mikich** [digrich/bubblechart-panel#1]
Chart is not show in combination with World Map plugin.
Grafana version=4.4.1
Data source Elasticsearch version: 5.5.0

Tested on Mac OS X (10.11.6)

Safari Error:
    `d3.tip is not a function. (In 'd3.tip()', 'd3.tip' is undefined)`
Chrome Error:
    `d3.tip is not a function`

Stack trace:
`TypeError: d3.tip is not a function
    at new bubbleChart (http://localhost:3000/public/plugins/digrich-bubblechart-panel/external/bubble.js?bust=1500934384332:51:18)
    at BubbleChartCtrl.addBubbleChart (http://localhost:3000/public/plugins/digrich-bubblechart-panel/bubble_ctrl.js?bust=1500934384332:258:39)
    at render (http://localhost:3000/public/plugins/digrich-bubblechart-panel/bubble_ctrl.js?bust=1500934384332:321:34)
    at f.eval (http://localhost:3000/public/plugins/digrich-bubblechart-panel/bubble_ctrl.js?bust=1500934384332:324:29)
    at f.emit (http://localhost:3000/public/app/boot.74ebeed4.js:62:13842)
    at a.emit (http://localhost:3000/public/app/boot.74ebeed4.js:62:15727)
    at BubbleChartCtrl.a.render (http://localhost:3000/public/app/boot.74ebeed4.js:56:2030)
    at BubbleChartCtrl.onDataReceived (http://localhost:3000/public/plugins/digrich-bubblechart-panel/bubble_ctrl.js?bust=1500934384332:118:30)
    at f.emit (http://localhost:3000/public/app/boot.74ebeed4.js:62:13409)
    at a.emit (http://localhost:3000/public/app/boot.74ebeed4.js:62:15727)`

**Comment by digrich** [comment]
I am not able to reproduce this issue.  What's the stat method under Options tab you are using? 
Just to confirm, the same query and settings work without world map plugin?
